#!/usr/bin/env python3

import datetime
import os

DATE = datetime.datetime.now().strftime("%d-%m-%y %H:%M:%S")
LOG = "/media/eiji/Compartilhamento/log_linux_bkp.out"
QLDISTRO = 'Ubuntu 22.04'

with open(LOG, "a") as log_file:
    log_file.write("=========================================\n")
    log_file.write(f"Relatório da Máquina: {os.uname()[1]}\n")
    log_file.write(f"Distro: {QLDISTRO}\n")
    log_file.write(f"Data/Hora: {DATE}\n")
    log_file.write("Iniciando Bacukp do Linux\n")
    log_file.write("=========================================\n\n")
print('')

print("=========================================\n")
print(f"Relatório da Máquina: {os.uname()[1]}\n")
print(f"Distro: {QLDISTRO}\n")
print(f"Data/Hora: {DATE}\n")
print("Iniciando Bacukp do Linux\n")
print("=========================================\n\n")
print('')
print("==========================================================")
print(f"Iniciando cópia do arquivo .bashrc - Data/Hora:{DATE}")
os.system("cp -rf /home/eiji/.bashrc /media/eiji/Compartilhamento/Linux/bkp_bashrc")
print("Os arquivo .bashrc sendo copiados")
with open(LOG, "a") as log_file:
    log_file.write(f"Iniciando cópia do arquivo .bashrc - Data/Hora:{DATE}\n")
    log_file.write("Os arquivo .bashrc sendo copiados\n")
    log_file.write(f"Cópia de .bashrc realizada com sucesso - Data/Hora:{DATE}\n")
    log_file.write("---\n\n")
print(f"Cópia de .bashrc realizada com sucesso - Data/Hora:{DATE}\n")
print("==========================================================")
print('')
print(f"Iniciando cópia do arquivo .ssh - Data/Hora:{DATE}")
os.system("cp -rf /home/eiji/.ssh /media/eiji/Compartilhamento/Linux/")
print("Os arquivo em .ssh sendo copiados")
with open(LOG, "a") as log_file:
    log_file.write(f"Iniciando cópia do arquivo em .ssh - Data/Hora:{DATE}\n")
    log_file.write("Os arquivo em .ssh sendo copiados\n")
    log_file.write(f"Cópia de .bashrc realizada com sucesso - Data/Hora:{DATE}\n")
    log_file.write("---\n\n")
print(f"Cópia de .bashrc realizada com sucesso - Data/Hora:{DATE}\n")
print("==========================================================")
print('')
print("==========================================================")
print(f"Iniciando cópia de Documentos - Data/Hora:{DATE}")
os.system("cp -rf /home/eiji/Documentos /media/eiji/Compartilhamento/Linux/")
print("Os arquivos estão sendo copiados")
with open(LOG, "a") as log_file:
    log_file.write(f"Iniciando cópia de Documentos - Data/Hora:{DATE}\n")
    log_file.write("Os arquivos estão sendo copiados\n")
    log_file.write(f"Cópia de Documentos realizada com sucesso - Data/Hora:{DATE}\n")
    log_file.write("---\n\n")
print(f"Cópia de Documentos realizada com sucesso - Data/Hora:{DATE}\n")
print("==========================================================")
print('')
print("==========================================================")
print(f"Iniciando cópia de Música - Data/Hora:{DATE}")
os.system("cp -rf /home/eiji/Música /media/eiji/Compartilhamento/Linux/")
print("Os arquivos estão sendo copiados")
with open(LOG, "a") as log_file:
    log_file.write(f"Iniciando cópia de Música - Data/Hora:{DATE}\n")
    log_file.write("Os arquivos estão sendo copiados\n")
    log_file.write(f"Cópia de Música realizada com sucesso - Data/Hora:{DATE}\n")
    log_file.write("---\n\n")
print(f"Cópia de Música realizada com sucesso - Data/Hora:{DATE}\n")
print("==========================================================")
print('')
print("==========================================================")
print(f"Iniciando cópia de Imagens - Data/Hora:{DATE}")
os.system("cp -rf /home/eiji/Imagens /media/eiji/Compartilhamento/Linux/")
print("Os arquivos estão sendo copiados")
with open(LOG, "a") as log_file:
    log_file.write(f"Iniciando cópia de Imagens - Data/Hora:{DATE}\n")
    log_file.write("Os arquivos estão sendo copiados\n")
    log_file.write(f"Cópia de Imagens realizada com sucesso - Data/Hora:{DATE}\n")
    log_file.write("---\n\n")
print(f"Cópia de Imagens realizada com sucesso - Data/Hora:{DATE}\n")
print("==========================================================")
print('')
with open(LOG, "a") as log_file:
    log_file.write("=========================================\n")
    log_file.write(f"Realizado bacukp do Linux\n")
    log_file.write(f"# Data/Hora: {DATE}\n")
    log_file.write("# Finalizado Bacukp do Linux\n")
    log_file.write("=========================================\n\n")